import { useMemo, useState } from 'react';
import { Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';

const A='#9184D9',BG='#161826',T='#E9E9ED',M='#9397AB',D='#3F424D';
const AM=[['Limpieza','Gel limpiador suave','Masajea 30 segundos sobre la piel húmeda y aclara con agua templada.'],['Tratamiento','Sérum de vitamina C','Dos o tres gotas. Extiende sin frotar y espera un minuto antes del siguiente paso.'],['Hidratación','Crema hidratante ligera','Una cantidad como una avellana, de dentro hacia fuera, cuello incluido.'],['Protección','Protector solar facial SPF50','Dos dedos de producto. Repite a media tarde si te da el sol.']];
const PM=[['Limpieza','Gel limpiador suave','Masajea 30 segundos sobre la piel húmeda y aclara con agua templada.'],['Tratamiento','Sérum de niacinamida 10%','Dos o tres gotas. Extiende sin frotar y espera un minuto antes del siguiente paso.'],['Tratamiento','Retinol encapsulado 0,3%','Dos o tres gotas. Extiende sin frotar y espera un minuto antes del siguiente paso.'],['Hidratación','Crema hidratante ligera','Una cantidad como una avellana, de dentro hacia fuera, cuello incluido.']];
export default function Ritual(){const {mode='am'}=useLocalSearchParams<{mode?:string}>();const items=mode==='pm'?PM:AM;const [i,setI]=useState(0);const p=items[i];const next=()=>i<items.length-1?setI(i+1):router.back();return <SafeAreaView style={styles.safe}><View style={styles.container}><View style={styles.top}><View style={styles.segments}>{items.map((_,n)=><View key={n} style={[styles.segment,{backgroundColor:n<i?A:n===i?A:D}]} />)}</View><Pressable onPress={()=>router.back()}><Text style={styles.close}>×</Text></Pressable></View><Text style={styles.kicker}>Paso {i+1} de {items.length} · {p[0]}</Text><Text style={styles.title}>{p[1]}</Text><Text style={styles.instruction}>{p[2]}</Text><View style={styles.photo}><Text style={styles.photoText}>foto</Text></View><View style={styles.tags}><Text style={styles.tag}>{mode==='am'?'Mañana':'Noche'}</Text><Text style={styles.outline}>Paso {i+1}</Text></View><View style={styles.bottom}><Pressable style={styles.primary} onPress={next}><Text style={styles.primaryText}>{i===items.length-1?'Hecho, terminar':'Hecho, siguiente paso'}</Text></Pressable><Pressable onPress={next}><Text style={styles.skip}>Saltar este paso hoy</Text></Pressable></View></View></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:BG},container:{flex:1,paddingHorizontal:22,paddingTop:18,paddingBottom:30},top:{flexDirection:'row',alignItems:'center',gap:14},segments:{flex:1,flexDirection:'row',gap:5},segment:{height:3,flex:1,borderRadius:99},close:{color:M,fontSize:27,lineHeight:27},kicker:{color:A,fontSize:10,letterSpacing:1,textTransform:'uppercase',marginTop:30},title:{color:T,fontSize:31,lineHeight:36,fontWeight:'600',marginTop:7},instruction:{color:'#CFD3E5',fontSize:14,lineHeight:21,marginTop:10,maxWidth:320},photo:{height:210,borderRadius:12,marginTop:24,backgroundColor:'#151827',alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:'#292B36'},photoText:{color:'#595D6C',fontSize:12},tags:{flexDirection:'row',gap:7,marginTop:12},tag:{backgroundColor:'#423A6A',color:'#F5F4FF',paddingHorizontal:9,paddingVertical:5,borderRadius:6,fontSize:11},outline:{borderWidth:1,borderColor:A,color:A,paddingHorizontal:9,paddingVertical:4,borderRadius:6,fontSize:11},bottom:{marginTop:'auto'},primary:{height:50,borderRadius:8,backgroundColor:A,alignItems:'center',justifyContent:'center'},primaryText:{color:BG,fontSize:14.5,fontWeight:'700'},skip:{textAlign:'center',color:'#75798C',fontSize:12.5,marginTop:13}});
