import { useEffect, useState } from 'react';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { generateRoutine } from '../lib/routine-engine';
import { loadProfile, loadRoutine, loadRoutineState, saveRoutine, saveRoutineState } from '../lib/storage';
import { products } from '../lib/products';
import type { SkinProfile, RoutineStep } from '../lib/types';
const A='#9184D9',BG='#161826',S='#232532',T='#E9E9ED',M='#9397AB',D='#3F424D';
const fallback:SkinProfile={skinType:'mixta',goals:['luz'],sensitivity:'algo',experience:'novata'};
const today=()=>new Date().toISOString().slice(0,10);
const yesterday=()=>{const d=new Date();d.setDate(d.getDate()-1);return d.toISOString().slice(0,10)};
function Nav(){return <View style={styles.nav}>{[['Hoy','/routine'],['Estante','/shelf'],['Escanear','/scanner'],['Progreso','/progress'],['Perfil','/profile']].map(([label,path])=><Pressable key={path} onPress={()=>router.push(path as never)} style={styles.navItem}><Text style={styles.navIcon}>{label==='Hoy'?'⌂':label==='Estante'?'▣':label==='Escanear'?'◎':label==='Progreso'?'◒':'○'}</Text><Text style={[styles.navLabel,label==='Hoy'&&styles.navActive]}>{label}</Text></Pressable>)}</View>}
export default function RoutineScreen(){
 const[mode,setMode]=useState<'am'|'pm'>('am');const[profile,setProfile]=useState<SkinProfile>(fallback);const[routine,setRoutine]=useState<{am:RoutineStep[];pm:RoutineStep[]}|null>(null);const[done,setDone]=useState<string[]>([]);const[streak,setStreak]=useState(0);const[notice,setNotice]=useState(true);
 useEffect(()=>{(async()=>{const p=await loadProfile();const actual=p??fallback;setProfile(actual);const saved=await loadRoutine<{am:RoutineStep[];pm:RoutineStep[]}>();const r=saved??generateRoutine(actual);setRoutine(r);if(!saved)await saveRoutine(r);const state=await loadRoutineState();setDone(state.completed);setStreak(state.streak)})()},[]);
 if(!routine)return <SafeAreaView style={styles.safe}><View style={styles.loading}><Text style={styles.title}>Preparando tu rutina…</Text><Text style={styles.meta}>Personalizando cada paso para tu piel.</Text></View></SafeAreaView>;
 const items=mode==='am'?routine.am:routine.pm;const count=items.filter(x=>done.includes(x.productId)).length;const pct=Math.round(count/Math.max(items.length,1)*100);const productFor=(id:string)=>products.find(p=>p.id===id);
 const toggle=async(id:string)=>{const next=done.includes(id)?done.filter(v=>v!==id):[...done,id];setDone(next);let nextStreak=streak;if(next.length>=routine.am.length+routine.pm.length&&streak===0)nextStreak=1;await saveRoutineState({completed:next,lastCompletedDate:next.length>=routine.am.length+routine.pm.length?today():undefined,streak:nextStreak});setStreak(nextStreak)};
 return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.body} showsVerticalScrollIndicator={false}>
 <View style={styles.header}><View><Text style={styles.kicker}>{new Date().toLocaleDateString('es-ES',{weekday:'long',day:'numeric',month:'long'})}</Text><Text style={styles.title}>{mode==='am'?'Buenos días':'Buenas noches'}</Text></View><Pressable onPress={()=>router.push('/profile')}><Text style={styles.skin}>Piel {profile.skinType}</Text></Pressable></View>
 {notice&&<View style={styles.notice}><View style={styles.bar}/><View style={{flex:1}}><Text style={styles.noticeKicker}>TU RUTINA PERSONALIZADA</Text><Text style={styles.noticeText}>Hemos elegido {items.length} pasos según tu piel, objetivos y tolerancia.</Text></View><Pressable onPress={()=>setNotice(false)}><Text style={styles.x}>×</Text></Pressable></View>}
 <View style={styles.progressCard}><View style={styles.row}><Text style={styles.meta}>{count} de {items.length} pasos hechos</Text><Text style={styles.meta}>Racha de {streak} días</Text></View><View style={styles.track}><View style={[styles.fill,{width:`${pct}%`}]}/></View></View>
 <View style={styles.segment}><Pressable onPress={()=>setMode('am')} style={[styles.seg,{borderColor:mode==='am'?A:D}]}><Text style={[styles.segText,mode==='am'&&styles.accent]}>Mañana</Text></Pressable><Pressable onPress={()=>setMode('pm')} style={[styles.seg,{borderColor:mode==='pm'?A:D}]}><Text style={[styles.segText,mode==='pm'&&styles.accent]}>Noche</Text></Pressable></View>
 <Pressable style={styles.primary} onPress={()=>router.push({pathname:'/ritual',params:{mode}})}><Text style={styles.primaryText}>Empezar la rutina paso a paso</Text></Pressable>
 {items.map((item,i)=>{const p=productFor(item.productId);if(!p)return null;const isDone=done.includes(item.productId);return <Pressable key={`${item.productId}-${i}`} onPress={()=>toggle(item.productId)} style={styles.step}><View style={[styles.check,isDone&&styles.checkDone]}><Text style={styles.checkText}>{isDone?'✓':''}</Text></View><View style={{flex:1}}><Text style={styles.stepKicker}>Paso {i+1} · {p.category}</Text><Text style={[styles.stepName,isDone&&styles.completed]}>{p.name}</Text><Text style={styles.desc}>{p.description}</Text><View style={styles.tags}><Text style={styles.tag}>{item.frequency}</Text><Text style={styles.outline}>{item.reason}</Text></View></View></Pressable>})}
 <View style={styles.suggestion}><Text style={styles.stepKicker}>Seguridad con activos</Text><Text style={styles.suggestionText}>La app separa retinol y ácido salicílico en noches distintas para evitar sobrecargar la rutina.</Text><View style={styles.actions}><Pressable onPress={()=>router.push('/actives')} style={styles.secondary}><Text style={styles.secondaryText}>Ver semana</Text></Pressable><Pressable onPress={()=>router.push('/shelf')} style={styles.secondary}><Text style={styles.secondaryText}>Ver estante</Text></Pressable></View></View>
 </ScrollView><Nav/></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:BG},body:{padding:20,paddingTop:18,paddingBottom:110,gap:12},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end'},kicker:{color:A,fontSize:10,letterSpacing:1.2,textTransform:'uppercase'},title:{color:T,fontSize:28,fontWeight:'600',marginTop:5},skin:{color:M,backgroundColor:'#292B31',paddingHorizontal:10,paddingVertical:5,borderRadius:8,fontSize:11},notice:{flexDirection:'row',backgroundColor:'#2B2741',borderRadius:8,padding:12,gap:10,alignItems:'flex-start'},bar:{width:3,backgroundColor:A,borderRadius:4,alignSelf:'stretch'},noticeKicker:{color:'#D2CEFD',fontSize:10,letterSpacing:1},noticeText:{color:'#F5F4FF',fontSize:13.5,lineHeight:19,marginTop:4},x:{color:M,fontSize:20,lineHeight:18},progressCard:{backgroundColor:S,borderRadius:8,padding:12},row:{flexDirection:'row',justifyContent:'space-between'},meta:{color:M,fontSize:12},track:{height:4,backgroundColor:D,borderRadius:99,marginTop:9},fill:{height:4,backgroundColor:A,borderRadius:99},segment:{flexDirection:'row',gap:8},seg:{flex:1,padding:9,borderWidth:1,borderRadius:8,alignItems:'center'},segText:{color:M,fontSize:13.5},accent:{color:A},primary:{minHeight:48,borderRadius:8,backgroundColor:A,alignItems:'center',justifyContent:'center'},primaryText:{color:BG,fontSize:14.5,fontWeight:'700'},step:{flexDirection:'row',gap:12,padding:12,borderRadius:8,backgroundColor:S},check:{width:26,height:26,borderRadius:13,borderWidth:1,borderColor:D,alignItems:'center',justifyContent:'center'},checkDone:{backgroundColor:A,borderColor:A},checkText:{color:BG,fontWeight:'800'},stepKicker:{color:A,fontSize:10,letterSpacing:1,textTransform:'uppercase'},stepName:{color:T,fontSize:16,fontWeight:'500',marginTop:3},completed:{opacity:.5,textDecorationLine:'line-through'},desc:{color:M,fontSize:12,lineHeight:17,marginTop:2},tags:{flexDirection:'row',gap:6,marginTop:7,flexWrap:'wrap'},tag:{backgroundColor:'#292B31',color:'#F3F5FE',fontSize:10.5,paddingHorizontal:8,paddingVertical:4,borderRadius:6},outline:{borderWidth:1,borderColor:A,color:A,fontSize:10.5,paddingHorizontal:8,paddingVertical:3,borderRadius:6},suggestion:{borderWidth:1,borderColor:'#423A6A',borderRadius:8,padding:13,gap:7},suggestionText:{color:T,fontSize:13,lineHeight:19},actions:{flexDirection:'row',gap:8},secondary:{flex:1,minHeight:42,borderWidth:1,borderColor:D,borderRadius:8,alignItems:'center',justifyContent:'center'},secondaryText:{color:T,fontSize:12.5},nav:{position:'absolute',bottom:0,left:0,right:0,height:82,paddingBottom:20,paddingTop:9,backgroundColor:'#161826',borderTopWidth:1,borderTopColor:'#292B31',flexDirection:'row',justifyContent:'space-around'},navItem:{alignItems:'center',minWidth:58},navIcon:{color:'#75798C',fontSize:19,height:23},navLabel:{color:'#75798C',fontSize:10},navActive:{color:A},loading:{flex:1,justifyContent:'center',alignItems:'center',gap:8}});
