import { useRef, useState } from 'react';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { addToShelf } from '../lib/shelf';
import { products } from '../lib/products';
const A='#9184D9',BG='#161826',S='#232532',T='#E9E9ED',M='#9397AB',D='#3F424D';
export default function Scanner(){const [permission,requestPermission]=useCameraPermissions();const [state,setState]=useState<'camera'|'loading'|'result'>('camera');const [saved,setSaved]=useState(false);const camera=useRef<CameraView>(null);const found=products.find(p=>p.id==='bha')!;
if(!permission)return <SafeAreaView style={styles.safe}><View style={styles.center}><Text style={styles.title}>Preparando cámara…</Text></View></SafeAreaView>;
if(!permission.granted)return <SafeAreaView style={styles.safe}><View style={styles.body}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Volver</Text></Pressable><View style={styles.center}><Text style={styles.title}>Necesitamos acceso a tu cámara</Text><Text style={styles.copy}>La cámara se usa para fotografiar la etiqueta del producto. No se activa hasta que tú lo permitas.</Text><Pressable style={styles.primary} onPress={requestPermission}><Text style={styles.primaryText}>Permitir cámara</Text></Pressable></View></View></SafeAreaView>;
const snap=async()=>{if(state!=='camera')return;setState('loading');try{await camera.current?.takePictureAsync({quality:.65,skipProcessing:true});}catch{}setTimeout(()=>setState('result'),1100)};
return <SafeAreaView style={styles.safe}><View style={styles.body}><View style={styles.head}><Pressable onPress={()=>router.back()}><Text style={styles.back}>‹ Volver</Text></Pressable><Text style={styles.headTitle}>Escanear producto</Text><View style={{width:55}}/></View>{state==='camera'?<><Text style={styles.subtitle}>Encuadra la etiqueta del producto</Text><View style={styles.viewer}><CameraView ref={camera} style={StyleSheet.absoluteFill} facing="back"/><View style={styles.guide}/></View><Pressable style={styles.shutter} onPress={snap}><View style={styles.shutterInner}/></Pressable></>:state==='loading'?<><View style={styles.viewer}><View style={styles.loadingCircle}/><Text style={styles.loadingLabel}>Analizando…</Text></View><Text style={styles.loadingText}>Leyendo la etiqueta y buscando coincidencias…</Text></>:<View style={styles.result}><Text style={styles.kicker}>PRODUCTO RECONOCIDO · 94%</Text><Text style={styles.name}>{found.name}</Text><Text style={styles.copy}>{found.description}</Text><View style={styles.tags}><Text style={styles.tag}>Noche</Text><Text style={styles.tag}>Ácido salicílico</Text></View><View style={styles.warning}><Text style={styles.warningTitle}>Compatibilidad</Text><Text style={styles.warningText}>No lo uses la misma noche que el retinol. Miranda Glow lo alternará automáticamente.</Text></View><Pressable style={styles.primary} onPress={async()=>{await addToShelf(found.id);setSaved(true)}}><Text style={styles.primaryText}>{saved?'✓ Guardado en mi estante':'Guardar en mi estante'}</Text></Pressable><Pressable onPress={()=>setState('camera')}><Text style={styles.secondary}>Escanear otro</Text></Pressable></View>}</View></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:BG},body:{flex:1,padding:20,paddingTop:18},head:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},headTitle:{color:T,fontSize:16,fontWeight:'600'},back:{color:A,fontSize:14},subtitle:{color:M,fontSize:13,marginTop:15},viewer:{height:370,borderRadius:14,overflow:'hidden',backgroundColor:'#101220',alignItems:'center',justifyContent:'center',marginTop:18},guide:{width:190,height:240,borderWidth:2,borderColor:A,borderRadius:10,backgroundColor:'transparent'},shutter:{width:66,height:66,borderRadius:33,borderWidth:3,borderColor:T,alignSelf:'center',marginTop:20,alignItems:'center',justifyContent:'center'},shutterInner:{width:52,height:52,borderRadius:26,backgroundColor:T},center:{flex:1,justifyContent:'center',alignItems:'center',padding:28},title:{color:T,fontSize:24,fontWeight:'600',textAlign:'center'},copy:{color:M,fontSize:13,lineHeight:19,marginTop:7},primary:{height:48,borderRadius:8,backgroundColor:A,alignItems:'center',justifyContent:'center',marginTop:18},primaryText:{color:BG,fontSize:14.5,fontWeight:'700'},loadingCircle:{width:64,height:64,borderRadius:32,borderWidth:2,borderColor:A},loadingLabel:{color:T,fontSize:13,marginTop:12},loadingText:{color:M,textAlign:'center',fontSize:12.5,marginTop:14},result:{marginTop:25,borderWidth:1,borderColor:'#423A6A',borderRadius:8,padding:15},kicker:{color:A,fontSize:10,letterSpacing:1},name:{color:T,fontSize:20,fontWeight:'600',marginTop:7},tags:{flexDirection:'row',gap:7,marginTop:10},tag:{color:'#F5F4FF',backgroundColor:'#423A6A',paddingHorizontal:8,paddingVertical:4,borderRadius:6,fontSize:10.5},warning:{marginTop:14,padding:11,borderRadius:7,backgroundColor:'#2B2741'},warningTitle:{color:A,fontSize:12,fontWeight:'600'},warningText:{color:T,fontSize:12,lineHeight:18,marginTop:3},secondary:{textAlign:'center',color:M,fontSize:13,marginTop:14}});
